name: Baked File System CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, crystal: latest }
          - { os: ubuntu-latest, crystal: nightly }
          - { os: macos-latest }
          - { os: windows-latest }
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Crystal
        uses: crystal-lang/install-crystal@d8ef131ecec0352ce0e39b81b0a6d95def58fe2f # Immutable pin from v1.9.2
        with:
          crystal: ${{ matrix.crystal }}

      - name: Download source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # Immutable pin from v7.0.1
        with:
          persist-credentials: false

      - name: Install dependencies
        run: shards install

      - name: Run tests
        run: crystal spec
